### ISSUE TITLE
Week02 - Redis - Rate Limiting(속도 제어)

### ISSUE THREAD

**Issue by youngkimi** [peaches-book-study/backend-BOOST#3]
### Assignee : youngkimi

--- ---
# 🍑 Sub-Topic 1. 조현수의 어쩌구

docker-compose.redis.yml
```yml
version: '3.7'
services:
    redis:
      image: redis:alpine
      command: redis-server --port 6379
      container_name: redis_boot
      hostname: redis_boot
      labels:
        - "name=redis"
        - "mode=standalone"
      ports:
        - 6379:6379
```

### 문자열을 활용해서 속도 제어

빠르게 하면 실패하는 모습
![redis_request_rapidly](https://github.com/peaches-book-study/backend-BOOST/assets/139294219/b8d0d369-6069-4115-aa93-b1ed41d2b3bd)

하지만 천천히 하면 성공하죠?
![redis_request_slowly](https://github.com/peaches-book-study/backend-BOOST/assets/139294219/a4f65524-dfe4-4512-9051-7d2ebf0adebc)

### 해시를 활용해서 속도 제어

# 🍑 Sub-Topic 2. 조현수의 저쩌구

# 🍑 결론

--- ---
## Referenced by
-
